name: CI Deploy Next on GH Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set user $user and repo $repo
        env:
          user: brunoreis
          repo: em-tempo
      - name: show
        run: echo "user ${env.user} repo ${{ env.repo }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Starting deploy 🚀"
          check_for_duplicate_msg: false
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Correctly update package.json
        run: perl -pi -e 's/github.io\/em-tempo/github.io\/em-tempo\/${{ steps.extract_branch.outputs.branch }}/gi' ./package.json
      - name: cat package.json
        run: cat ./package.json
      - run: yarn
      - run: BASE_PATH=/em-tempo/${{ steps.extract_branch.outputs.branch }} NEXT_TARGET=serverless ./node_modules/next/dist/bin/next build
      - run: BASE_PATH=/em-tempo/${{ steps.extract_branch.outputs.branch }} NEXT_TARGET=serverless ./node_modules/next/dist/bin/next export
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}
          SINGLE_COMMIT: true
          id: deploy
      - name: Deploy Success
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Deploy successfully completed. ✅"
          check_for_duplicate_msg: false  
        if: ${{ env.DEPLOYMENT_STATUS == 'success' }}
      - name: Deploy Fail
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Deploy failed. ❌"
          check_for_duplicate_msg: false
        if: ${{ env.DEPLOYMENT_STATUS == 'failed' }}
      - name: PR Skipped
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "Deploy skipped. 🦘"
          check_for_duplicate_msg: false
        if: ${{ env.DEPLOYMENT_STATUS == 'skipped' }}
